version: "3.9"

volumes:
  postgres_data:
    driver: local

services:
  api:
    build: .
    ports:
      - "5000:5000"
    expose:
      - "5000"
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_DB: postgres
      KC_DB_PASSWORD: keycloak
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_USERNAME: keycloak
      KC_DB_URL_DATABASE: keycloak
    ports:
      - "8085:8080"
    depends_on:
      - postgres